# Wymowa linii StExt_Say dla TTS: klucz = CRC32 (nazwa OU), wartosc = tekst
# czytany przez lektora (pelne polskie znaki; skrypty gry sa ASCII).
# Generowane przez eleven_batch_say.ps1; edytuj przy zmianie tresci linii.
@{
    '7F248AE0' = 'Stój. Czuję na tobie Żar - cudze śmierci, które nosisz jak płaszcz. Większość ludzi nie czuje go, dopóki ich nie strawi.'
    '8F788D3B' = 'Nazywają nas Rycerzami Dusz. Błędne miano. Nie jesteśmy rycerzami. Jesteśmy tymi, którzy nauczyli się żywić śmiercią, zamiast przed nią uciekać.'
    'F6F9B880' = 'Chcesz mocy - widzę to, każdy chce. Ale moc Zakonu ma cenę. Większość płaci ją bez wahania... dopóki nie zrozumie, co oddała.'
    '1313AE25' = 'Wróć, gdy będziesz gotów złożyć przysięgę. I nie przychodź, jeśli szukasz litości. Tutaj jej nie ma.'
    'AB88E255' = 'Więc jednak wróciłeś. Dobrze. Słuchaj uważnie, bo powtórzę to tylko raz.'
    'A490E476' = 'Wybierzesz dwa żywioły. Tylko dwa. W nich urośniesz w siłę, jakiej nie zaznasz nigdzie indziej. Resztę - zapomnisz. Na zawsze. Zakon nie znosi połowiczności.'
    '37C00CAC' = 'Wybieraj rozważnie. Tej przysięgi nie cofniesz - a ja nie będę słuchał skarg.'
    '826896E9' = 'Z czym mam pracować? Dobądź żelaza, które ma przyjąć duszę.'
    '81FD5C6A' = 'Tysiąc sztuk złota. Rytuał ma cenę i nie ja ją ustalam.'
    '0DAFA7EE' = 'To żelazo nie zna żywiołu. Dusza nie ma się czego uchwycić - przynieś broń z pieczęcią albo perkiem.'
    '95D74D16' = 'Gotowe. Dusza wtopiona w ostrze - czujesz? Ono teraz pamięta, jak się zabija.'
    '55031339' = 'Nie dziś. Przeszłość Zakonu płaci się krwią - przynieś mi kolejną głowę, wtedy opowiem więcej.'
    '6C814358' = 'Słuchaj uważnie. Rzadko o tym mówię, a dwa razy nie powtarzam. Zapisz to sobie, jeśli musisz.'
    'EFF9FB01' = 'Sztuki Rycerza Dusz. Płaci się duszami bossów - złota tu nie przyjmuję, złoto jest dla kupców.'
    'B3721552' = 'Dziesięciu padło z twojej ręki. Zakon płaci swoje długi - wybierz pancerz i noś go tak, żeby następna dziesiątka bała się go z daleka.'
    '02CE2C8B' = 'Zakon wzywa - ty zabijasz. Taki jest układ. Arena czeka na wybrzeżu.'
    '56F7D3C8' = 'Cel na ten rozdział jest wybrany. Znajdź go, zabij i przynieś mi jego duszę. Bez duszy nie wracaj.'
    '71920E1B' = 'Żar Dusz ściąga umarłych, jak ścierwo ściąga wrony. Kaplica przestaje być bezpieczna.'
    'B5CB402F' = 'Wybrałem nowy dom dla Zakonu: starą wieżę na wybrzeżu. Problem w tym, że ktoś w niej już mieszka.'
    '81842977' = 'Upiory garnizonu. Wytnij je co do jednego - Zakon nie dzieli dachu z umarłymi, których sam nie zabił.'
    '2E9DAC89' = 'Wieża na wybrzeżu, na północ stąd. Wskazałem raz - drugi raz wskazuję palcem, trzeciego nie będzie.'
    '17ECDE66' = 'Wieża stoi pusta - czuję to stąd. Dobra robota, rycerzu.'
    'E83CB456' = 'Zakon przenosi się o świcie. Weź te dusze - należą się temu, kto oczyścił dom.'
    '02420450' = 'Weź Runę Zakonu. Zawsze zaprowadzi cię z powrotem do mnie.'
    'A4B79C08' = 'Dobądź żelazo, które mam przekuć. Młot nie bije w powietrze.'
    'D6566731' = 'Tego żelaza nie przekuję. Ono już wie, czym jest.'
    '9A664184' = 'Młot pamięta. Ręce pamiętają. Odbierz - to już nie jest ta sama broń.'
    'BBC9A8F6' = 'Nie pytaj o imię. Zostawiłem je w ogniu, dawno temu. Ogień go nie oddał.'
    '00FD20FD' = 'Kuję, bo ręce pamiętają to, czego głowa nie. Młot wie więcej ode mnie.'
    'CDD5FA21' = 'Ty śmierdzisz duszami, wędrowcze. Tyle ich nosisz... a wciąż ci mało.'
    '36BA6FE9' = 'Dusze... tak. Może wśród nich znajdę okruch tego, czym byłem. Pójdę. Ale niczego nie obiecuję.'
    '0F0A5260' = 'Nie wiem. Zostały po mnie trzy rzeczy... rozsypane tam, gdzie umarli. Znajdź je, a może i mnie znajdziesz.'
    '8BBEF306' = 'Coś wraca. Twarz przy kowadle. Jeszcze dwa... jeszcze jeden... Przynieś resztę.'
    # --- Mistrz Mrocznych Rycerzy (Droga Beliara) ---
    '5B521683' = 'Służyć? Jeszcze niczym nie jesteś. Ale masz w sobie ten sam głód, co my - głód, który karmi tylko krew wroga.'
    '553D4A7B' = 'Na wybrzeżu wciąż oddycha paladyn Aldrik. Odbierz mu ten oddech. Po cichu, jak przystało na sługę Beliara.'
    '46373FE4' = 'Wróć, gdy jego serce ucichnie.'
    '90D76D54' = 'Czuję jego śmierć na twoich rękach. Dobrze. Weź ten znak - Beliar już na ciebie patrzy.'
    '320491F2' = 'Paladyni strzegą relikwii, która paruje ich światłem. Ich siła płynie ze świętości - odbierzmy im ją.'
    'D27D2E69' = 'Zabij jej stróża, Paladyna Rolanda, i splugaw to świadectwo. Niech poczują, jak ich bóg milczy.'
    '8CD0CCCC' = 'Daj. Czujesz ten chłód? To ich bóg odwraca wzrok. Zostaw ją tutaj - niech gnije u stóp Beliara.'
    '9A2654CF' = 'Dwaj bracia w bieli, Gerhard i Wolker, poznali twoje imię. To błąd, który naprawisz nożem.'
    '9A9850FE' = 'Obaj mają zamilknąć tej nocy. Na zawsze. Nikt, kto zna nasze twarze, nie doczeka świtu.'
    'B007BAFB' = 'Cisza. Nareszcie. Dwa imiona wykreślone z księgi żywych - i nikt ich już nie wpisze z powrotem.'
    '6F2C17E2' = 'Kapitan Ortwin zbiera ludzi przeciw nam. Rozetnij ten węzeł u samego źródła.'
    '824FDB3C' = 'Reszta to tylko miecze bez ręki. Zabij jego, a rozsypią się sami.'
    '4A35910E' = 'Bez głowy ciężko dowodzić. Ich zapał gaśnie razem z nim. Został już tylko jeden - najjaśniejszy.'
    '0CA5F53D' = 'Został jeden - Paladyn Lord Isgaroth, ich najjaśniejszy płomień. Zgaś go, a przestaniesz być nikim.'
    '259C7079' = 'Pójdzie z gwardią. Przebij się i wbij mu ostrze pod serce. Dziś kończysz drogę - a z tej drogi nie ma powrotu.'
    '20EB7A5D' = 'Krew ich najjaśniejszego wsiąkła w twoje ręce. Beliar cię widzi - a ja, po raz pierwszy, nie widzę w tobie nikogo.'
    '66EA2C1E' = 'Weź to ostrze. Pije światło tak, jak inni piją krew. Od dziś jesteś Mroczną Ręką Beliara.'
    '5439EE75' = 'Wskazałem raz. Nie każ mi powtarzać - Beliar nie ceni tępych ostrzy.'
    # --- Kowal / Mistrz Zakonu: linie zmienione w tej sesji (immersja), wymowa PL ---
    '037D866B' = 'Żywioł siedzi w stali. Odbierz żelazo z sakwy i załóż je.'
    '2F7D2F62' = 'Żadnej magii - sama stal, kuta do końca. Takie ostrze nie zawodzi. Odbierz je z sakwy.'
    '57636879' = 'Nagi rycerz to trup. Załóż pancerz, w który mam wtopić duszę.'
    'A34E3AE1' = 'Dusza wrosła w stal. Załóż pancerz - broni cię teraz tak, jak bronił swojego pana.'
    '4D69FE4E' = 'Sztuki Rycerza Dusz. Płaci się duszami poległych - złota tu nie przyjmuję, złoto jest dla kupców.'
    'FDFD647D' = 'I weź tę runę. Zaprowadzi cię prosto do naszej nowej siedziby, gdy tylko zechcesz.'
    # --- Mroczny Nauczyciel: moce Beliara (aury) ---
    '58E9529B' = 'Gniew Beliara wstępuje w twoje ramię. Załóż ten kamień, a każdy cios stanie się cięższy.'
    '69E86FD1' = 'Kto cię tknie, sam się zrani. Beliar nie wybacza dotyku.'
    '11CF084F' = 'Twoja skóra stwardnieje jak sumienie grzesznika. Ostrza będą się na niej łamać.'
    '0C24325C' = 'Niech ich czary wrócą do nich. Mrok jest lustrem, które nie kłamie.'
    '417AA94C' = 'Twoje ciosy zostawią klątwę, która żre od środka. Beliar lubi powolne konanie.'
    '3289A071' = 'Wszystko, co żyje, służy Beliarowi jako pożywienie. Twoje ostrze będzie głodniejsze.'
    '5A599E38' = 'Otwórz bramę, a stanie przy tobie demon. To najwyższy dar - i najcięższy ciężar.'
    '600718A8' = 'Twoje aury piją więcej mroku. Każda z nich uderza teraz mocniej.'
    # --- Odprawy z nazwaniem lokacji (cele rozrzucone po landmarkach) ---
    '6E4077A7' = 'Na wybrzeżu, przy latarni morskiej, wciąż oddycha paladyn Aldrik. Odbierz mu ten oddech. Po cichu, jak przystało na sługę Beliara.'
    'C3000A63' = 'Zabij jej stróża, Paladyna Rolanda - stoi przy rozstaju dróg pod klasztorem. Splugaw to świadectwo, niech poczują, jak ich bóg milczy.'
    'DF5D3FC6' = 'Dwaj bracia w bieli, Gerhard i Wolker, zaszyli się na farmie Lobarta u bram miasta. Poznali twoje imię - to błąd, który naprawisz nożem.'
    '0A49BCD8' = 'Kapitan Ortwin zbiera ludzi przeciw nam przy wielkim młynie. Rozetnij ten węzeł u samego źródła.'
    'D95BF1BD' = 'Został jeden - Paladyn Lord Isgaroth, ich najjaśniejszy płomień. Zaszył się na odludnej farmie Sekoba, na południu. Zgaś go, a przestaniesz być nikim.'
    # --- Kowal: sklep ze zbrojami ---
    '3033867C' = 'Nakułem tego przez lata. Zapłać uczciwie, a wybierzesz, co chcesz.'
    '8B1EC9DB' = 'Bierz. Kuta nie moją ręką, ale posłuży. Rangę podbijesz gdzie indziej.'
    # --- Mistrz Zakonu: podbijanie rangi zbroi ---
    '17AEC8F8' = 'Nagi rycerz to trup. Załóż pancerz, który mam wynieść ku legendzie.'
    'EA3D5DD8' = 'Ta stal już nosi legendę. Wyżej nie sięgnie.'
    'F13E70C7' = 'Legenda ma cenę w złocie. Wróć, gdy ją uzbierasz.'
    '7E541FE6' = 'Bez dusz stal pozostanie zwykłym żelazem. Przynieś ich więcej.'
    'E112EAF7' = 'Ta stal nie przyjmie legendy.'
    '9F1C5F97' = 'Stal pamięta każdą duszę. Ranga rośnie - załóż ją z plecaka, by poczuć różnicę.'
    # --- Mistrz Mrocznych Rycerzy: wojna z Łowcami Demonów ---
    'A3F9D392' = 'Łowcy demonów polują na wszystko, co nosi cień Beliara - a ty niesiesz go jak sztandar.'
    'A1698D90' = 'Zagnieździli się w dworku za farmą Onara, w lesie nad jeziorem. Wytnij ich gniazdo. Ich mistrz Angel ma paść pierwszy.'
    'D25FFCC9' = 'Ich mistrz martwy, gniazdo wyrżnięte. Krzyż nie ochronił ich przed Beliarem.'
    '9A18A950' = 'Weź ich własną kuszę. Przekułem ją w ogniu - teraz pije światło, któremu służyła.'
    '91E53021' = 'W dworku za farmą Onara, w lesie nad jeziorem. Zbiorę ich tam dla ciebie - idź i skończ to.'
    # --- Lowcy: gniazdo w porcie (po korekcie lokalizacji) ---
    'D0AA1A29' = 'Zagnieździli się w porcie, przy nabrzeżu. Wytnij ich gniazdo. Ich mistrz ma paść pierwszy.'
    '8D304BD1' = 'W porcie, przy nabrzeżu - tam trzymają swoje gniazdo. Idź i skończ to.'
    # --- Lowcy: dworek odrestaurowany + Belmond ---
    '082365CE' = 'Odbudowali stary dworek za farmą Onara, w lesie nad jeziorem, i właśnie się tam ściągają. Wytnij to gniazdo - ich mistrz ma paść pierwszy.'
    '637CA7A2' = 'I strzeż się jednego. Ich dowódca to tylko głos, ale Belmond to ostrze - jego zbroja pamięta więcej demonów niż ty ludzi. Przy nim nosi coś, co warto zabrać.'
    'CC85BD94' = 'W dworku za farmą Onara, w lesie nad jeziorem. Tam się ściągnęli - idź i skończ to.'
    # --- Lowcy: garnizon Zakonu w dworku ---
    'DAB08F34' = 'Masz rację. Puste gniazdo szybko znajduje nowe ptaki.'
    '0CA296D9' = 'Poślę tam braci. Od dziś w dworku płonie ogień Beliara - i biada temu, kto spróbuje go zgasić.'
    # --- DK R3: Ogien za ogien (Nauczyciel) ---
    'DFA89D83' = 'Zgasiłeś ich najjaśniejszy płomień - i światło to poczuło. Innos przysłał rachunek: inkwizytor Malachiasz zszedł ze statku i pyta o człowieka z twoją twarzą.'
    'C357BED5' = 'Rozsiadł się w tawernie przy trakcie, z dwoma egzorcystami. Czeka, aż przyjdziesz się tłumaczyć. Idź. Wytłumacz mu się ostrzem - wszystkim trzem.'
    '40C623FF' = 'Przysłali ogień, a wrócił im popiół. Dobrze. Niech następny statek wiezie już tylko strach.'
    'E46481AB' = 'Beliar patrzy na ciebie coraz dłużej. Czuję, jak twoja aura ciemnieje - noś ją z dumą.'
    # --- Kowal R3: Mlot, ktory pamieta ---
    '9999166F' = 'Młot. Zawsze jest młot. Mój leży tam, gdzie go rzuciłem - w ruinach nad drogą, przy trollowej dolinie.'
    'E22A1C48' = 'Gnieździ się tam teraz banda. Herszt kuje moim młotem podkowy. PODKOWY. Przynieś mi go, zanim całkiem go pohańbi.'
    '1BBB86CA' = 'Ręce go pamiętają. Trzon wytarł się tam, gdzie zawsze. Więc to było moje.'
    '3C6780D5' = 'Pierwszy okruch wrócił. Kuźnia to poczuje - i ty poczujesz. Zostały dwa.'
    # --- DK R3 Q7 "Ucho Innosa" (Nauczyciel) ---
    'DC841BA0' = 'Inkwizytor nie spadł z nieba. Ktoś mu ciebie wskazał - ucho Innosa w porcie. Brat Kasjan, przebrany za żebraka, liczy twoje kroki i sprzedaje je za odpust.'
    '20805FB3' = 'Najął dwa ostrza, bo wie, że po niego przyjdziesz. Ucisz wszystkich trzech - martwe ucho nie słyszy.'
    'D9116149' = 'Port znowu twój. Ale jeden im uciekł - kaznodzieja Ezechiel wsiadł na łódź nim domknąłeś sieć.'
    'CEDF70E4' = 'Popłynął do Górniczej Doliny, do wygnańców ze starych kopalni. Buduje tam tłum. Nie skończyłeś - skończysz tam.'
    # --- DK R3 Q8 "Kaznodzieja w Dolinie" (Nauczyciel) ---
    '25D43969' = 'Górnicza Dolina to nie Khorinis. Tam nie ma murów ani strażników - jest kamień, ork i ludzie, których świat już raz wyrzucił. Ezechiel obiecuje im niebo za twoją głowę.'
    'EC4BEB02' = 'Przejdź przełęcz i znajdź go. Będzie z fanatykami, głęboko, gdzie echo niesie kazania. Zgaś go - i niech Dolina zapamięta, czyj to teraz cień.'
    'D670D506' = 'Kazanie ucichło w pół słowa. Słyszałem to aż tutaj - a raczej Beliar słyszał, i podzielił się ze mną.'
    '9FAC7236' = 'Kościół wysłał na ciebie ogień, ucho i głos. Zgasiłeś wszystkie trzy. Odtąd to nie ty się kryjesz - to oni. Weź to ostrze; nasiąkło ich strachem.'
    # --- Kowal: wyniesienie broni ku legendzie ---
    '1D4CC461' = 'Pokaż mi ostrze, nie pustą dłoń. Dobądź broni, którą mam wynieść.'
    '18B34DEE' = 'Ta stal już jest legendą. Wyżej nie pójdzie - nawet w moich rękach.'
    '061B1750' = 'Legenda kosztuje. Wróć ze złotem.'
    '59200689' = 'Ogień, co nie gaśnie, karmi się duszami. Przynieś ich więcej.'
    '46176070' = 'Ta stal nie przyjmie legendy. Przynieś inne ostrze.'
    '12AC4FC9' = 'Czujesz? Stal cięższa o jedną legendę. Dobądź jej z plecaka, by poznać różnicę.'
}
